apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secret
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    JWT_SECRET: AgAzDdtSXWRI3tbBcDbChcFXhlqnmp5/OC15bqwmqrbS+qJ99ih8gSEt02U+/3I5CyjNyB+kDXTPq9aOjsjmSCSM8J3F22liHmCOLKByAUpVv539dW4XeqASbQNmObtbduAxBTXs2MEhXkfNY2Pa1F9vuo3Ot+p87P1Ro7Da3boLnXgNPr1ya3P3xGNdNRkhZ8ADLxs8rPJOAJ2vd1T4A2QdhkF85dvC2tnBb6NPu2sl0vi8QdrbLf+ip0eroGWeQBcQtWgbVUeQrwvxb2AKx4M6xuD1dO4oNCF3d26qbtJ3OmcQUaaXQYuc1Y2CPuQZ91JP4vsKOjOa9FQPXTt4SLepS66DKduRGBLlVM1u7uSv7PMQAsFHgO4CIAHiuVK5/P90h2NvunhE9yUSjbl8HR3z/XDA1/j3vBp6RcQ9j4HbkELAXAxrUfy/ZU1SZhGlkQQJcKQjwVZQ7RU1gLxfoMB3m5z3HfQNWwG8KdbhkKkv4DrQfPNanwnOuSt8rO7e1NqqjrlzNeblBD8C+Po2GR85kSHJe7gbpVaY6eNYuzvaDTv0P6zpBmFMl1S1mp/whQ0847bEXlQCIoU+Wt8cvOTexdxjsHihrglCKYGm6+JlUEx2KZKXGfsi25ciVaZ7buU3N/G6vPECsfA48TxWxhloAftssdS6J/tXGZA+qymNrYC4kG+7Yr9E+pPXFjlrJSs14VjI41s=
    DATABASE_URL: AgB+bFYKsHaO8v4VWg2DmMftF7eu+ozZDDiTsqD5jP5H/cq6ex++KRRbzpbZP+g/Bm4yacvpN7y2JDZwrxsPP4I4xN7ZBYrxPdtp/Vdg3V/EAX7oW1T7+3AVTMuHpqV1TUVhrlwVQp9bFn+SExDwbHLOU/gIZRxk9c80mnd4fcaIhZOZKELmISrUS1b6sVDcszk3xE/IP0vv9n0f2940IuoF/J7Y0PBdBEeRMC7hzv16O6YnQimGB3B4qtSWtnMJkE8eb2bDsUoTjDUdE1WWPrt/VX+MnghmiDvoBQCtJUuSUJbPADQi2omeUTYwrCDUqkRszqaHX3jpbGhyv9ntYn8r4cfiuKf/FT9UZCEnDIeDom2R8bXS2PGijuAfaeYuXS9CeWOzovJcdNWAnR0rcj3QWibhZ511rt6rx6oJa/wHXn1/uEAIXMvMfEDJQf9LeTpLycIW9c5wg3Dt6AnS36ucqZhs7Ny7R1NCITbADzqc+vyNLaPIh7u0Y2L+qtJzKMz9etTAAuxQhuCHFHwpYt3eFq1xXwtinnZs/5ErJlrMMdc3fVsOARGKbD6e9MAxAnLb55ERTYs/UVF5+YRSqv7PGcpSTJFju0yc6d2V3pzuaINBrIErRe9K3N4pdgHiZliNrWmSqszpypoeGncvO7+ydqygC/ZHD4DTJ7d5Cd04qex/uUxHEr9uRezbXaL7MSGJSpmCfQakpDoi9qVtYsqZfUN1WqBNHDER7kQFDs44woGWxsnjScLd7/PlwqybFawG/eYxC+sJfCTBaCTgdC/7gdCWe4caBDEAZVw=
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: default
    type: Opaque
