apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    POSTGRES_USER: AgBQR+sgaWp1ixNLrlOJxtbuWy00KDt1Get6JGkmsvjXF8ahBO6j1cu+taKdQI81onrHLTl12AW7XXEL79+jvcHcoplgiqHJ43WTrwUWoA0cjtAtzsCQCiN2ioY0UyvkguvmGHt0fyFBdTM6Nv2OB/hha9D6TC+jPN6EHvs4Ab+fGM7fcb22i+fApKp8/PvNLda9wwZdagBzihEH3nimP3r2QJB8QvoHzAjfiCxqJYX2jPXZ0miYz2Dl53WGxcMdpu9iXu+0ltWJORwP+0IoXXW6J4VbTUDsLAJrJTLstO1TOYjda5xGLw0Oli5Ckxt0PJUpI60qmONQdPSDpGkeF8yRW/yyFKeTv6DieY35nQjU21Wnku/d3WvHujAMLABfj8PZS+E5ihNoyeHJIxhi/agJV3io61clo9Cyf3xOsmjJH5m939lPIEM75PPxLQ6EOoeTzmeYCFIDLKLk2TzrVEgm9S2xoVWnJ98zQKtKXCfcOZij1HW45icl5HgQJQJu3BkiMm4LuNYl0RpEwse6L1EYsgMO3AqC8FJsRKezEyLZqx70DjhbljwcCP08oKa7E3o1NSQjM7TYZS0NgYk846uDGuFpjiWIp1beoBrZE0KYEwWSpLUO8Tvc8hLmd6M5ECsYoeag6X/JeS5N1omuF9w15cCiYDHbT627ujFCLBrk71n9IlxfST6pkajuxayjUjG8ZFFpsmu6XsfLajc=
    POSTGRES_PASSWORD: AgAiNzA8haxcVjlfgxsT+xgv/FJf8Vp9PK2DMkeF3BRzbHuLAtwTKquDdFJaux4XO1fauRcp55XGN9ww1cUWi2rKWCTwyLRIUDSSDeL/OGXKJJ+n/0Fc6b/3YiiKvVVDAujN29hYXvr+cSnDDRzvIuDnGOxFnbxk5PnQ9p7uMWEP6tTCtsQ/nxtZ/LJ0/LbKSTWQdIMcafhnictYqc3jBH/1xtDlgXHg3yh8IpVRSpjo+FEi4J3QBasjXgAen0ci3BGofw8/JGkQngCEjGPkRndryqCbkp+OQe+LK9O1CyhOK8i7ICV2Yw1E6SVNc+DLhydTMdnarmEszJN+RXrfaAQEIa4fE56mt7qmLIPYUz8l5C6gdsZQKnV2Ty9oFF6VJMLnG+geXunxpk9wpiHWDS/Z8jYsHbcNRP8n2rTjeLJMZmzJqy/S8w+OLnAIgSRq1YcDebHFzOja74nqShlqsYGDcj+WONb0ZG/zENNQI0oxFldGZfGPIPLvVUdkaqHX4qPbRw7NB684rLFEf4yxhLO1xQ31E9sCYbUMEZOvou72SA9fJ0peFet+UQKGIM+jO61933GDaGHberR8ifes6mw7w9sCCuTrrrWO2aTbANjM8lxPZfadZ9kcRdGuqlhu6TlGh0QHceuJMO50WZatDM1JrgSBFh+X380dKuly92Y+ZVbpgfPTleMn6EwfF5+PkDHMY7ma5Enkzf/Oa+IMMUomP+UD5w==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default
    type: Opaque
